### PR TITLE
feat: add husky with lint-staged

### PR DESCRIPTION
**Pull request by idleberg**
The combination of `lint-staged` and `husky` will prevent code that didn't pass ESLint or ran through Prettier from being committed. Personally, I couldn't live with this anymore :)

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
I am not a fan of Husky due to its issues such as [this one](https://github.com/typicode/husky/issues/673)

I prefer Lefthook for managing the Git hooks. 
https://github.com/evilmartians/lefthook

**Comment by aminya** [comment]
Lefthook supports linting staged by itself. I have a configuration file somewhere. I can update this branch some time later.

**Comment by aminya** [comment]
Well. It is better that we add it to all the repositories through our repository-sync script.

**Comment by idleberg** [comment]
> Lefthook supports linting staged by itself

Interesting. Their migration guide from husky/lint-staged is a bit ambiguous about that. But knowing that it's possible, that guide can be interpreted that way :)

**Comment by aminya** [comment]
This is the config I was referring to:
```
pre-commit:
  parallel: true
  commands:
    format:
      run: npx prettier --write {staged_files}
```

**Comment by aminya** [comment]
I have noticed that Git hooks run very slow when terminal isn't used. I tested Atom and Github desktop

**Pull request closed without merging**
